# Generated by Django 6.0 on 2026-01-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_account_generated_card_number_account_generated_cvc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='loans_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='account',
            name='mortgage_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
