# Generated by Django 6.0 on 2026-01-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_account_loans_due_account_mortgage_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transfer_count',
            field=models.IntegerField(default=0),
        ),
    ]
